figure;
subplot(3,2,1), plot(Case4_RawObserve,'DisplayName','Case4_RawObserve');
xlabel('time');
ylabel('velocity value');
title('E4');
subplot(3,2,2), plot(Case7_RawObserve,'DisplayName','Case7_RawObserve');
xlabel('time');
ylabel('velocity value');
title('N1');
subplot(3,2,3), plot(Case5_RawObserve,'DisplayName','Case5_RawObserve');
xlabel('time');
ylabel('velocity value');
title('E5');
subplot(3,2,4), plot(Case8_RawObserve,'DisplayName','Case8_RawObserve');
xlabel('time');
ylabel('velocity value');
title('N2');
subplot(3,2,5), plot(Case6_RawObserve,'DisplayName','Case6_RawObserve');
xlabel('time');
ylabel('velocity value');
title('E6');
subplot(3,2,6), plot(Case9_RawObserve,'DisplayName','Case9_RawObserve');
xlabel('time');
ylabel('velocity value');
title('N3');

figure;
result = hmmviterbi(Case4ObSequence,TRANS,EMIS);
subplot(3,2,1), plot(result,'DisplayName','Case4_RawObserve');
xlabel('time');
ylabel('States');
title('E4');
result = hmmviterbi(Case7ObSequence,TRANS,EMIS);
subplot(3,2,2), plot(result,'DisplayName','Case7_RawObserve');
xlabel('time');
ylabel('States');
title('N1');
result = hmmviterbi(Case5ObSequence,TRANS,EMIS);
subplot(3,2,3), plot(result,'DisplayName','Case5_RawObserve');
xlabel('time');
ylabel('States');
title('E5');
result = hmmviterbi(Case8ObSequence,TRANS,EMIS);
subplot(3,2,4), plot(result,'DisplayName','Case8_RawObserve');
xlabel('time');
ylabel('States');
title('N2');
result = hmmviterbi(Case6ObSequence,TRANS,EMIS);
subplot(3,2,5), plot(result,'DisplayName','Case6_RawObserve');
xlabel('time');
ylabel('States');
title('E6');
result = hmmviterbi(Case9ObSequence,TRANS,EMIS);
subplot(3,2,6), plot(result,'DisplayName','Case9_RawObserve');
xlabel('time');
ylabel('States');
title('N3');